name: tmb
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - bedtools=2.29.2=hc088bd4_0
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2020.6.20=hecda079_0
  - certifi=2020.6.20=py36h9f0ad1d_0
  - click=7.1.1=pyh8c360ce_0
  - coloredlogs=14.0=py36h9f0ad1d_1
  - curl=7.69.1=h33f0ec9_0
  - cyvcf2=0.11.7=py36hce88a48_0
  - htslib=1.9=h4da6232_3
  - humanfriendly=8.1=py36h9f0ad1d_1
  - krb5=1.17.1=h2fd8d38_0
  - ld_impl_linux-64=2.34=h53a641e_0
  - libblas=3.8.0=16_openblas
  - libcblas=3.8.0=16_openblas
  - libcurl=7.69.1=hf7181ac_0
  - libdeflate=1.2=h516909a_1
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgfortran-ng=7.3.0=hdf63c60_5
  - liblapack=3.8.0=16_openblas
  - libopenblas=0.3.9=h5ec1e0e_0
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - llvm-openmp=10.0.0=hc9558a2_0
  - mosdepth=0.2.6=hfb13731_0
  - ncurses=6.1=hf484d3e_1002
  - numpy=1.18.1=py36h7314795_1
  - openssl=1.1.1g=h516909a_0
  - pandas=1.0.5=py36h830a2c2_0
  - pcre=8.44=he6710b0_0
  - pip=20.0.2=py_2
  - pybedtools=0.8.1=py36h5202f60_2
  - pysam=0.8.3=py36h84994c4_6
  - python=3.6.10=h8356626_1010_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pytz=2020.1=pyh9f0ad1d_0
  - pyyaml=5.3.1=py36h8c4c3a4_0
  - readline=8.0=hf8c457e_0
  - setuptools=46.1.3=py36h9f0ad1d_0
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.30.1=hcee41ef_0
  - tk=8.6.10=hed695b0_0
  - wheel=0.34.2=py_1
  - xz=5.2.5=h516909a_0
  - yaml=0.2.3=h516909a_0
  - zlib=1.2.11=h516909a_1006
prefix: /data/users/tgutman/.conda/envs/tmb

